### ISSUE TITLE
Issue running cooperative tests

### ISSUE THREAD

**Issue by remidebette** [willemt/pytest-asyncio-cooperative#1]
Hi!

I am starting to play around with asyncio and I wanted to try writing some HTTP client code against some known APIs.
As in this case the unit tests of such a client library would consist in several HTTP calls, written in `async` style, running them asyncronously makes sense.

I found this repo from your [comment](https://github.com/pytest-dev/pytest-asyncio/issues/69#issuecomment-602148284) and I thought to give it a try.

Could you provide some help about setting the tests up? 
The code is in my repo.

prismic-httpx is a repo I am building forked from an existing synchronous library. 
I rewrote it using `async` and [httpx](https://www.python-httpx.org/) in a way that all unit tests are passing again.
Now, I made [this PR](https://github.com/remidebette/prismic-httpx/pull/3) where I switched to pytest-asyncio-cooperative.

I changed the pytest marks and redefined the fixtures as `async`, but I have this error on local during collection:
```python
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/remi/.local/share/virtualenvs/prismic-httpx-YnEdHj-v/bin/python
cachedir: .pytest_cache
rootdir: /home/remi/PycharmProjects/prismic-httpx
plugins: asyncio-0.10.0, asyncio-cooperative-0.4.1
collecting ... collected 57 items


test_prismic.py::test_expiration ERROR                                   [  1%]
test setup failed
args = (), kwargs = {}
loop = <_UnixSelectorEventLoop running=False closed=False debug=False>
setup = <function pytest_fixture_setup.<locals>.wrapper.<locals>.setup at 0x7fbf72e64830>

    def wrapper(*args, **kwargs):
        loop = kwargs['event_loop']
        if strip_event_loop:
            del kwargs['event_loop']
    
        async def setup():
            res = await f(*args, **kwargs)
            return res
    
>       return loop.run_until_complete(setup())

../../../.local/share/virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.7/site-packages/pytest_asyncio/plugin.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.7/asyncio/base_events.py:566: in run_until_complete
    self.run_forever()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def run_forever(self):
        """Run until stop() is called."""
        self._check_closed()
        if self.is_running():
            raise RuntimeError('This event loop is already running')
        if events._get_running_loop() is not None:
            raise RuntimeError(
>               'Cannot run the event loop while another loop is running')
E           RuntimeError: Cannot run the event loop while another loop is running

/usr/lib/python3.7/asyncio/base_events.py:524: RuntimeError
ERROR                                      [  3%]
test setup failed
args = (), kwargs = {}
loop = <_UnixSelectorEventLoop running=False closed=False debug=False>
setup = <function pytest_fixture_setup.<locals>.wrapper.<locals>.setup at 0x7fbf72e257a0>

    def wrapper(*args, **kwargs):
        loop = kwargs['event_loop']
        if strip_event_loop:
            del kwargs['event_loop']
    
        async def setup():
            res = await f(*args, **kwargs)
            return res
    
>       return loop.run_until_complete(setup())

../../../.local/share/virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.7/site-packages/pytest_asyncio/plugin.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.7/asyncio/base_events.py:566: in run_until_complete
    self.run_forever()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def run_forever(self):
        """Run until stop() is called."""
        self._check_closed()
        if self.is_running():
            raise RuntimeError('This event loop is already running')
        if events._get_running_loop() is not None:
            raise RuntimeError(
>               'Cannot run the event loop while another loop is running')
E           RuntimeError: Cannot run the event loop while another loop is running

/usr/lib/python3.7/asyncio/base_events.py:524: RuntimeError
```

**Comment by willemt** [comment]
hi thanks for trying to use this plugin.

Can you please try uninstalling pytest-asyncio? I can see in your test output asyncio-0.10.0 is installed. It seems like pytest-asyncio hijacks ALL `async` tests, so it has to be uninstalled.

**Comment by remidebette** [comment]
Hi, I had removed the pytest-asyncio dependency from [the branch](https://github.com/two-armed-bandit/prismic-httpx/pull/3/files) I shared with you, but indeed it was still installed. I recreated the virtualenv from scratch and now it works.

It is really fast, I am impressed.
Also as shared in your docs, all the synchronous tests are simply ignored by pytest?
It means when using this library, I must put them all to async and mark them with `@pytest.mark.asyncio_cooperative`. It is kind of tedious, there is no alternative?

More importantly, one thing is still blocking me. 
2 unit tests are not passing anymore

```python
from aiocache import Cache

@fixture()
async def cache():
    return Cache(Cache.MEMORY)


@pytest.mark.asyncio_cooperative
async def test_set_get(cache):
    await cache.set("foo", "bar", 3600)
    assert await cache.get("foo") == "bar"


@pytest.mark.asyncio_cooperative
async def test_expiration(cache):
    await cache.set("toto", "tata", 2)
    await asyncio.sleep(3)
    assert await cache.get("toto") is None
```

The error I get is quite cryptic.
As it does not get to my code, I cannot debug further.

```python
==================================================================================== FAILURES ====================================================================================
________________________________________________________________________________ test_expiration _________________________________________________________________________________

>   item.runtest = lambda: result.result()

../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:349: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:214: in test_wrapper
    fixture_values, teardowns = await fill_fixtures(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

item = <Function test_expiration>

    async def fill_fixtures(item):
        fixture_values = []
        teardowns = []
        for arg_name in function_args(item.function):
            # FIXME: not sure how to handle duplicate fixture names
>           assert len(item._fixtureinfo.name2fixturedefs[arg_name]) == 1
E           assert 2 == 1
E             +2
E             -1

../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:193: AssertionError

```

**Comment by remidebette** [comment]
Oh actually, it was another error my full tests to run. (synchronous and asynchronous)
The execution failed when reaching tests depending on the following fixture:

```python
@fixture()
async def api():
    return prismic.Api(fixture_api, token, Cache(Cache.MEMORY), None)

```
tests complain of `api` being a coroutine instead of the plain Api object.


Basically, pytest-asyncio forced me to put all my fixtures as async. 
But in the case of pytest-asyncio-cooperative, it would seem that declaring async fixtures without awaiting before return breaks the tests.
It is unexpected

**Comment by willemt** [comment]
Thanks for the bug report. Please try version 0.7? It supports synchronous fixtures inside async tests.

**Comment by remidebette** [comment]
Hi,

Thanks for the reactivity.
Unfortunately, it still does not work with version 0.8.3 .
My tests based on synchronous str or objects fixtures fail. Even if I set the functions as async.
The same would work fine with pytest-asyncio for instance.

If I do something like this:

```python
import pytest
from pytest import fixture


@fixture()
def api_url():
    return "http://micro.prismic.io/api"


@pytest.mark.asyncio_cooperative
async def test_get_api(api_url):
    assert api_url == "http://micro.prismic.io/api"
```


error:
```
=================================== FAILURES ===================================
_________________________________ test_get_api _________________________________

>   item.runtest = lambda: result.result()

../../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:371: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:224: in test_wrapper
    fixture_values, teardowns = await fill_fixtures(item)
../../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:209: in fill_fixtures
    value, teardowns2 = await fill_fixture_fixtures(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

_fixtureinfo = FuncFixtureInfo(argnames=('api_url',), initialnames=('api_url',), names_closure=['api_url'], name2fixturedefs={'api_url': (<FixtureDef argname='api_url' scope='function' baseid='tests/test_coop.py'>,)})
fixture = <FixtureDef argname='api_url' scope='function' baseid='tests/test_coop.py'>
item = <Function test_get_api>

    async def fill_fixture_fixtures(_fixtureinfo, fixture, item):
    
        if inspect.isasyncgenfunction(fixture.func) or isinstance(
            fixture.func, CachedAsyncGen
        ):
            fixture_values, teardowns = await _fill_fixture_fixtures(
                _fixtureinfo, fixture, item
            )
    
            # Cache the module call
            if fixture.scope in ["module"]:
                if not isinstance(fixture.func, CachedAsyncGen):
                    fixture.func = CachedAsyncGen(fixture.func)
    
            gen = fixture.func(*fixture_values)
            value = await gen.__anext__()
            return value, teardowns + [gen]
    
        elif inspect.iscoroutinefunction(fixture.func) or isinstance(
            fixture.func, CachedFunction
        ):
            fixture_values, teardowns = await _fill_fixture_fixtures(
                _fixtureinfo, fixture, item
            )
    
            # Cache the module call
            if fixture.scope in ["module"]:
                if not isinstance(fixture.func, CachedFunction):
                    fixture.func = CachedFunction(fixture.func)
    
            value = await fixture.func(*fixture_values)
            return value, teardowns
    
        # Regular fixture
        # FIXME: we should use more of pytest's fixture system
        elif inspect.isgeneratorfunction(fixture.func):
            gen = fixture.func()
            return gen.__next__(), [gen]
    
        # It's a parameterization
        # FIXME: we should use more of pytest's fixture system
        elif fixture.params:
            request = item._request
            request.param = item._pyfuncitem.callspec.params[fixture.argname]
            val = fixture.func(request)
            return val, []
    
        else:
>           raise Exception(
                f"Something is strange about the fixture '{fixture.func.__name__}'.\n"
                f"Please create an issue with reproducible sample on github."
            )
E           Exception: Something is strange about the fixture 'api_url'.
E           Please create an issue with reproducible sample on github.

../../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:192: Exception
=========================== short test summary info ============================
FAILED test_coop.py::test_get_api - Exception: Something is strange about the...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 failed in 0.06s ===============================

```

Also my previously stated bug is still here:
```python
from aiocache import Cache

@fixture()
async def cache():
    return Cache(Cache.MEMORY)


@pytest.mark.asyncio_cooperative
async def test_set_get(cache):
    await cache.set("foo", "bar", 3600)
    assert await cache.get("foo") == "bar"


@pytest.mark.asyncio_cooperative
async def test_expiration(cache):
    await cache.set("toto", "tata", 2)
    await asyncio.sleep(3)
    assert await cache.get("toto") is None
```

The error I get is quite cryptic.
As it does not get to my code, I cannot debug further.

```python
==================================================================================== FAILURES ====================================================================================
________________________________________________________________________________ test_expiration _________________________________________________________________________________

>   item.runtest = lambda: result.result()

../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:349: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:214: in test_wrapper
    fixture_values, teardowns = await fill_fixtures(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

item = <Function test_expiration>

    async def fill_fixtures(item):
        fixture_values = []
        teardowns = []
        for arg_name in function_args(item.function):
            # FIXME: not sure how to handle duplicate fixture names
>           assert len(item._fixtureinfo.name2fixturedefs[arg_name]) == 1
E           assert 2 == 1
E             +2
E             -1

../../.virtualenvs/prismic-httpx-YnEdHj-v/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:193: AssertionError

```

**Comment by willemt** [comment]
Please try it now
c0df999c16aa8fae298185718497c562a327bcd3 -> fixes fixture that uses the same name as a builtin fixture (eg. `cache`)
eb1a21460243f4bf7473b8b1a6c65e0cac0b16a2 -> fixes fixtures that return (instead of yield)

**Comment by remidebette** [comment]
Hi,

Again, thanks for your reactivity.
Mostly, my tests pass as expected right now.

I had one remaining concern that I could not replicate simply, but it is in the same [PR](https://github.com/remidebette/prismic-httpx/pull/3/commits/74b4653257cea3da37b32e8b1bccd5722c01ea89).
If you click on the above link to see my last commit, I had to remove the `async` keyword before the `api` fixture.
(Indeed there is no reason to keep this fixture as async since it is synchronous. So I actually removed it)

I think I introduced those artificially async fixtures at some point because of a rule in pytest-asyncio or in pytest-asyncio-cooperative.
In my case, more simple examples simply work, for some reason only this one broke.

Just for my understanding, what is the should that should be used here: if I declare a `async` fixture, I should await it in the tests? or the framework should take care of it?
(If the rule is non trivial, a fixture example in the README might help)

Here is the error that appears for all tests depending on this fixture:

code:
```python
from pytest import fixture
import prismic

@fixture()
async def api(fixture_api, token):
    return prismic.Api(fixture_api, token, Cache(Cache.MEMORY), None)

def test_get_ref_master(api):
    assert api.get_ref("Master").ref == "UgjWQN_mqa8HvPJY"

```

error:
```python
=================================== FAILURES ===================================
_____________________________ test_get_ref_master ______________________________

api = <coroutine object api at 0x7f3048769dc0>

    def test_get_ref_master(api):
>       assert api.get_ref("Master").ref == "UgjWQN_mqa8HvPJY"
E       AttributeError: 'coroutine' object has no attribute 'get_ref'

test_prismic.py:287: AttributeError
```

**Comment by remidebette** [comment]
I detailed my synchronous fixture issue with a reproducible example in https://github.com/willemt/pytest-asyncio-cooperative/issues/3

**Comment by willemt** [comment]
> Just for my understanding, what is the rule that should be used here: if I declare an async fixture, I should await it in the tests? or the framework should take care of it?
(If the rule is non trivial, a fixture example in the README might help)

If your test is marked with `@pytest.mark.asyncio_cooperative`, and your fixture has `async`, then you don't need to do anything. No `await` is required. asyncio-cooperative will deliver the fixture as a variable into your test (it will NOT deliver it as a coroutine). This mimics the behaviour of regular synchronous pytest fixtures. I will add a note to the README.

**Synchronous tests using async fixtures**
This is not supported and will not be supported. This is out of scope for asyncio-cooperative.

**Synchronous fixtures that have parent fixtures**
This issue was caused by asyncio-cooperative not supporting fixtures that themselves have parent fixtures (and so on). This was fixed by db82fcf7619c7ca582ae75f1be0cff96771d34de, and works in version 0.9.0

**Comment by remidebette** [comment]
With the various fixes you provided from version 0.7 to 0.9.0 
I would say that now this project is safe to add async tests to an existing code base.

(From my point of view it is even more interesting than pytest-asyncio since the performance is better and the async tests can live alongside a synchronous test base)
